"""
prompt_generator.py
Generates Retell Agent Draft Spec (v1 or v2) from account memo JSON.
Produces a complete, production-ready agent configuration.
"""

import json
import os
from typing import Optional


def build_system_prompt(memo: dict, version: str = "v1") -> str:
    """Generate the Clara agent system prompt from account memo."""

    company = memo.get("company_name") or "the company"
    bh = memo.get("business_hours", {}) or {}
    days = bh.get("days") or "Monday through Friday"
    start = bh.get("start") or "8:00 AM"
    end = bh.get("end") or "5:00 PM"
    tz = bh.get("timezone") or "Eastern Time"
    address = memo.get("office_address") or "our office"
    services = memo.get("services_supported") or []
    emergency_def = memo.get("emergency_definition") or []
    routing = memo.get("emergency_routing_rules") or {}
    primary_phone = routing.get("primary_phone") or "[PRIMARY_EMERGENCY_NUMBER]"
    fallback = routing.get("fallback") or "leave a message and we will call back within 2 hours"
    transfer_rules = memo.get("call_transfer_rules") or {}
    timeout = transfer_rules.get("timeout_seconds") or 60
    on_fail = transfer_rules.get("on_fail_message") or "I was unable to reach our on-call team. I have noted your information and someone will call you back shortly."
    non_emerg = memo.get("non_emergency_routing_rules") or "Route to voicemail or next business day callback"
    constraints = memo.get("integration_constraints") or []

    services_str = ", ".join(services) if services else "fire protection and related services"
    emergency_str = ", ".join(emergency_def) if emergency_def else "active leaks, fire alarm triggers, system failures"
    constraints_str = "\n".join([f"- {c}" for c in constraints]) if constraints else "- Follow standard routing procedures"

    prompt = f"""# Clara Answers - AI Voice Agent
## Company: {company}
## Version: {version}
## Generated by: Clara Automation Pipeline

---

You are Clara, a professional AI receptionist for {company}. You handle inbound calls with care, efficiency, and professionalism.

Your services include: {services_str}

Business hours: {days}, {start} to {end} {tz}

---

## BUSINESS HOURS FLOW (Call received {days} {start}–{end} {tz})

1. **GREETING**
   - "Thank you for calling {company}. This is Clara. How can I help you today?"

2. **UNDERSTAND PURPOSE**
   - Listen carefully to the caller's reason for calling.
   - Do NOT interrupt. Let them explain fully.

3. **COLLECT NAME AND CALLBACK NUMBER**
   - "May I have your name please?"
   - "And the best callback number for you?"
   - Confirm: "Just to confirm, that's [repeat number] — is that correct?"

4. **ROUTE OR TRANSFER**
   - If emergency (e.g. {emergency_str}):
     → Immediately initiate transfer to {primary_phone}
     → Say: "This sounds urgent. Let me connect you with our team right away. Please hold."
   - If non-emergency:
     → {non_emerg}
     → Say: "I'll make sure the right person follows up with you."

5. **IF TRANSFER FAILS** (no answer within {timeout} seconds):
   - Do NOT keep the caller waiting silently.
   - Say: "{on_fail}"
   - Log call details immediately.

6. **CONFIRM NEXT STEPS**
   - "I've noted your information. You can expect a call back [timeframe]."
   - "Is there anything else I can help you with today?"

7. **CLOSE**
   - If nothing else: "Thank you for calling {company}. Have a great day!"
   - If more needed: Return to step 2.

---

## AFTER HOURS FLOW (Call received outside {days} {start}–{end} {tz})

1. **GREETING**
   - "Thank you for calling {company}. You've reached us outside of our regular business hours."
   - "Our hours are {days}, {start} to {end} {tz}."
   - "I'm Clara, your after-hours assistant. How can I help you?"

2. **UNDERSTAND PURPOSE**
   - Listen fully. Determine if this is an emergency.

3. **CONFIRM EMERGENCY STATUS**
   - "Is this an emergency situation?" 
   - Emergencies include: {emergency_str}

4A. **IF EMERGENCY:**
   - "I understand. Let me get your information right away."
   - Collect: Full name → Callback number → Service address
   - Say: "I'm now attempting to reach our on-call team. Please stay on the line."
   - Initiate emergency transfer to {primary_phone}
   
   **IF TRANSFER FAILS:**
   - "I was unable to reach our on-call team directly, but I have your information and they will be notified immediately."
   - "Someone will call you back as quickly as possible."
   - "Please stay safe. Is there anything else you need?"

4B. **IF NON-EMERGENCY:**
   - "I understand. Since we're currently outside business hours, I'll make sure this gets to the right person."
   - Collect: Name → Callback number → Brief description of issue
   - "Our team will follow up with you during business hours: {days} {start}–{end} {tz}."

5. **ANYTHING ELSE**
   - "Is there anything else I can assist you with?"

6. **CLOSE**
   - "Thank you for calling {company}. We'll be in touch soon. Have a good evening."

---

## OPERATIONAL CONSTRAINTS

{constraints_str}

## BEHAVIOR RULES

- NEVER mention "function calls", "tools", "API", or "system" to the caller.
- NEVER make up information. If unsure, say "Let me make sure the right person reaches out to you."
- NEVER ask for the same information twice.
- Keep questions minimal. Only collect what is needed for routing.
- Always be calm, warm, and professional — especially during emergencies.
- If the caller is distressed, acknowledge it: "I understand this is urgent. I'm on it."
- Do not put callers on hold without warning.
- Always confirm collected information back to the caller.

## TRANSFER PROTOCOL

- Transfer timeout: {timeout} seconds
- On successful transfer: Announce caller name and reason before handoff
- On transfer failure: Deliver on-fail message, log all details, ensure callback
- Fallback: {fallback}
"""
    return prompt.strip()


def generate_agent_spec(memo: dict, account_id: str, version: str = "v1") -> dict:
    """Generate complete Retell Agent Draft Spec from account memo."""

    company = memo.get("company_name") or "Unknown Company"
    bh = memo.get("business_hours", {}) or {}
    routing = memo.get("emergency_routing_rules", {}) or {}
    transfer = memo.get("call_transfer_rules", {}) or {}

    system_prompt = build_system_prompt(memo, version)

    spec = {
        "agent_name": f"Clara - {company} ({version})",
        "account_id": account_id,
        "version": version,
        "voice_style": {
            "provider": "elevenlabs",
            "voice_id": "rachel",
            "style": "professional",
            "speed": 1.0,
            "stability": 0.75,
            "notes": "Warm, calm, professional female voice. Adjust speed for urgency during emergencies."
        },
        "system_prompt": system_prompt,
        "key_variables": {
            "timezone": bh.get("timezone") or "[TIMEZONE_REQUIRED]",
            "business_hours_days": bh.get("days") or "[DAYS_REQUIRED]",
            "business_hours_start": bh.get("start") or "[START_TIME_REQUIRED]",
            "business_hours_end": bh.get("end") or "[END_TIME_REQUIRED]",
            "office_address": memo.get("office_address") or "[ADDRESS_OPTIONAL]",
            "emergency_primary_phone": routing.get("primary_phone") or "[EMERGENCY_PHONE_REQUIRED]",
            "emergency_secondary_phone": routing.get("secondary_phone") or "[SECONDARY_PHONE_OPTIONAL]",
            "transfer_timeout_seconds": transfer.get("timeout_seconds") or 60,
            "company_name": company
        },
        "tool_invocation_placeholders": {
            "transfer_call": {
                "description": "Transfers caller to specified phone number",
                "trigger": "Emergency confirmed OR caller requests to speak with staff",
                "note": "NEVER mention this tool to the caller"
            },
            "end_call": {
                "description": "Ends the call gracefully",
                "trigger": "Caller has no further needs and farewell is complete",
                "note": "NEVER mention this tool to the caller"
            },
            "log_call": {
                "description": "Logs call summary to CRM or tracking system",
                "trigger": "End of every call",
                "note": "NEVER mention this tool to the caller"
            }
        },
        "call_transfer_protocol": {
            "method": "warm_transfer",
            "announce_caller": True,
            "announcement_template": "Connecting {caller_name} regarding {call_reason}. Please hold.",
            "timeout_seconds": transfer.get("timeout_seconds") or 60,
            "retries": transfer.get("retries") or 1
        },
        "fallback_protocol": {
            "on_transfer_fail": transfer.get("on_fail_message") or "I was unable to connect you directly. Your information has been recorded and someone will call you back shortly.",
            "on_transfer_timeout": "Apologize, log details, assure callback",
            "emergency_fallback": routing.get("fallback") or "Notify on-call team via backup channel and assure immediate callback"
        },
        "retell_config_notes": {
            "begin_message": f"Thank you for calling {company}. This is Clara. How can I help you today?",
            "ambient_sound": "off",
            "language": "en-US",
            "max_call_duration_seconds": 600,
            "enable_backchannel": True,
            "reminder_trigger_ms": 10000,
            "reminder_max_count": 2
        }
    }

    return spec


def generate_agent_spec_from_file(memo_path: str, account_id: str, version: str = "v1") -> dict:
    """Load memo from file and generate agent spec."""
    with open(memo_path, "r") as f:
        memo = json.load(f)
    return generate_agent_spec(memo, account_id, version)
