"""
storage.py
Handles all file storage operations for Clara Automation Pipeline.
Outputs go to /outputs/accounts/<account_id>/<version>/
"""

import json
import os
from datetime import datetime, timezone
from typing import Optional, Union

# Base output directory (relative to project root)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUTS_DIR = os.path.join(BASE_DIR, "outputs", "accounts")


def get_account_output_dir(account_id: str, version: str) -> str:
    path = os.path.join(OUTPUTS_DIR, account_id, version)
    os.makedirs(path, exist_ok=True)
    return path


def save_account_artifact(account_id: str, version: str, filename: str,
                           data: Union[dict, str], raw: bool = False) -> str:
    """Save artifact to outputs/accounts/<account_id>/<version>/<filename>"""
    out_dir = get_account_output_dir(account_id, version)
    filepath = os.path.join(out_dir, filename)

    with open(filepath, "w", encoding="utf-8") as f:
        if raw or isinstance(data, str):
            f.write(data)
        else:
            json.dump(data, f, indent=2, ensure_ascii=False)

    return filepath


def load_account_artifact(account_id: str, version: str, filename: str) -> Optional[Union[dict, str]]:
    """Load artifact from outputs directory. Returns None if not found."""
    out_dir = get_account_output_dir(account_id, version)
    filepath = os.path.join(out_dir, filename)

    if not os.path.exists(filepath):
        return None

    with open(filepath, "r", encoding="utf-8") as f:
        if filename.endswith(".json"):
            return json.load(f)
        return f.read()


def create_task_tracker_item(account_id: str, memo: dict, version: str = "v1") -> dict:
    """
    Create a task tracker entry (local JSON log — simulates Asana/Linear).
    In production, this would POST to Asana API.
    """
    task = {
        "task_id": f"TASK_{account_id}_{version}_{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}",
        "account_id": account_id,
        "company_name": memo.get("company_name") or "Unknown",
        "version": version,
        "status": "pending_review",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "open_questions": memo.get("questions_or_unknowns") or [],
        "extraction_method": memo.get("_extraction_method"),
        "notes": f"Auto-generated by Clara Pipeline A ({version}). Review and confirm before deploying to Retell."
    }

    # Save task log
    tasks_dir = os.path.join(BASE_DIR, "outputs", "task_log")
    os.makedirs(tasks_dir, exist_ok=True)
    task_path = os.path.join(tasks_dir, f"{task['task_id']}.json")
    with open(task_path, "w") as f:
        json.dump(task, f, indent=2)

    print(f"[Storage] Task created: {task['task_id']}")
    return task


def list_all_accounts() -> list:
    """List all account IDs in outputs directory."""
    if not os.path.exists(OUTPUTS_DIR):
        return []
    return [d for d in os.listdir(OUTPUTS_DIR)
            if os.path.isdir(os.path.join(OUTPUTS_DIR, d))]


def get_account_summary() -> list:
    """Get summary of all processed accounts."""
    accounts = []
    for account_id in list_all_accounts():
        acc_dir = os.path.join(OUTPUTS_DIR, account_id)
        versions = [d for d in os.listdir(acc_dir) if os.path.isdir(os.path.join(acc_dir, d))]
        memo_v1 = load_account_artifact(account_id, "v1", "memo.json")
        memo_v2 = load_account_artifact(account_id, "v2", "memo.json")
        accounts.append({
            "account_id": account_id,
            "company_name": (memo_v2 or memo_v1 or {}).get("company_name") or "Unknown",
            "versions_present": sorted(versions),
            "has_v2": "v2" in versions,
            "open_questions": len((memo_v2 or memo_v1 or {}).get("questions_or_unknowns") or [])
        })
    return accounts
